version: '2'
services:
   api:
      build: .
      ports:
         - 80:80
         - 443:443
      depends_on:
         - mysql
         - rabbitmq
      environment:
         - MYSQL_USER=root
         - MYSQL_PASSWORD=password12345
         - MYSQL_DATABASE=first_db
         - MYSQL_HOST=mysql
         - MYSQL_PORT=3306
         - GOOGLE_SECRET=/usr/local/etc/google_secret.json
      volumes:
          - ./data/ssl:/etc/apache2/ssl
          - ./log:/log
      restart: always

   mysql:
      image: mysql:5.7
      expose:
         - 3306
      environment:
         - MYSQL_ROOT_PASSWORD=password12345
         - MYSQL_DATABASE=first_db
      volumes:
         - ./data/mysql:/var/lib/mysql
      restart: always

   rabbitmq:
      image: rabbitmq:3-management
      restart: always
      ports:
         - "35672:5672"
         - "15672:15672"
      volumes:
         - ./install/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
